### ISSUE TITLE
[DOCUMENTATION] Request for Supabase SQL Commands and Backend Structure

### ISSUE THREAD

**Issue by 1saifj** [mahmoodhamdi/Blogify#46]
Hello,

I would appreciate it if you could provide documentation or details regarding the Supabase backend structure used in this project, along with the specific SQL queries implemented.

This information would be incredibly helpful for better understanding and contributing to the project.

Thank you in advance for your assistance.

Best regards,  
Saif Aljanahi
Software Developer

**Comment by mahmoodhamdi** [comment]
Hi Saif,

Thank you for your request! I’m happy to inform you that I’ve added the documentation for the Supabase backend structure, along with the specific SQL queries implemented in the project. You can find this information in the README under the newly added section titled "Supabase Backend Structure."

If you have any further questions or need more details, feel free to ask. Your feedback is always appreciated!

Best regards,
Mahmoud Hamdi

**Comment by mahmoodhamdi** [comment]
Hi Saif,

Thank you for your request! I'm happy to inform you that we've added the documentation for the Supabase backend structure, along with the specific SQL queries implemented in the project. You can find this information in the README under the newly added section titled "Supabase Backend Structure."

This addition includes:
- An overview of the database schema
- Detailed structure and policies for the profiles and blogs tables
- Information about storage for blog images
- SQL for automatic profile creation on user signup

You can see the changes in PR #48: "docs: Add Supabase backend structure and SQL queries to documentation".

If you have any further questions or need more details, please don't hesitate to ask. Your feedback is always appreciated!

I'll be closing this issue now as it has been addressed. Thanks again for your contribution to improving our documentation.

Best regards,
Mahmoud Hamdi

**Comment by 1saifj** [comment]
Dear Mahmoud,

Thank you for adding the documentation. It looks great!

Best regards,
